### ISSUE TITLE
Google Search: bih and biw parameters

### ISSUE THREAD

**Issue by mattnotmax** [obsidianforensics/unfurl#101]
Great tool thanks Ryan!

Both `bih` and `biw` parameters in google search currently appear as generic 'URL parsing functions' 

![image](https://user-images.githubusercontent.com/39072319/97776724-b76c5b00-1bbe-11eb-808a-717a8bcf5913.png)

However, they appear to be well documented as testable that it equates to the browser windows height and width. This can be checked using something like: https://browsersize.com/

![image](https://user-images.githubusercontent.com/39072319/97776737-d36ffc80-1bbe-11eb-89ad-f3474c497fba.png)

Thanks again!

**Comment by obsidianforensics** [comment]
Thanks for flagging!
