### ISSUE TITLE
Website linked in repo description is unavailable with HTTPS

### ISSUE THREAD

**Issue by sebix** [obsidianforensics/unfurl#129]
The website linked in the repo's about section https://unfurl.link/ is dead, the server 162.255.119.33 refuses connections on port 443. Port 80 redirects to https://dfir.blog/unfurl/

![image](https://user-images.githubusercontent.com/199050/144457277-c0cbd174-6f70-4839-90a4-b577a86b1e95.png)

```
$ curl https://unfurl.link/
curl: (7) Failed to connect to unfurl.link port 443 after 316 ms: Connection refused
$ curl http://unfurl.link/
<a href='https://dfir.blog/unfurl/'>Found</a>.

```

**Comment by obsidianforensics** [comment]
Thanks for flagging this!

The unfurl.link domain doesn't have any associated site, it is just redirected to https://dfir.blog/unfurl/. I'm not aware of a way to make https://unfurl.link redirect (via Namecheap at least), so only http://unfurl.link does. I changed the link in the 'About' section to http://. Thanks again!
