### ISSUE TITLE
Receiving this error for both Offline Server and CLI tools

### ISSUE THREAD

**Issue by RandyRandleman** [obsidianforensics/unfurl#177]
Following directions on both attempts with PIP and GIT CLONE and still get the same issues. Unable to get it to run within the offline most: 

tl;dr:     warning_lists_dict['List of known Office 365 URLs'].list.remove('bit.ly')
ValueError: list.remove(x): x not in list

Can provide everything it is throwing back, but this is the primary issue with the CLI version. The Web Version I'm still getting 500 server errors on, but if CLI works, that would be tremendous.

**Comment by RandyRandleman** [comment]
Thank you!

**Comment by obsidianforensics** [comment]
Hey there, thanks for reporting. There were some changes in pymispwarninglists that Unfurl didn't handle well. I'm working on a fix. In the meantime, if you install an older version of pymispwarninglists (via pip or similar), Unfurl should work again.

**Comment by RandyRandleman** [comment]
Thank you, Ryan!!
