### ISSUE TITLE
protobuf dependency inquiry

### ISSUE THREAD

**Issue by msramalho** [obsidianforensics/unfurl#188]
Hi, 
I see [here](https://github.com/obsidianforensics/unfurl/commit/f32ab05f316eb8ccf5cb89550738cbbe28937ada) that protobuf 4.21 was claimed incompatible with this project. 

I opened this issue to ask why and if that is still the case, since that was over a year ago.

The reason is that fixing the protobuf version to 3 means that any other libraries that require a more recent version of protobuf cannot be installed alongside unfurl.

**Comment by obsidianforensics** [comment]
Thanks for raising this issue - let me take another look as to why.

**Comment by msramalho** [comment]
Thanks for addressing this so quickly :100:
