### ISSUE TITLE
KSUID parser

### ISSUE THREAD

**Issue by obsidianforensics** [obsidianforensics/unfurl#19]
**Description**
KSUIDs are time-sortable, so we should parse this as a timestamp and the random component. 

**Examples**
- 0ujsszwN8NRY24YaXiTIE2VWDTS

**References**
- https://github.com/segmentio/ksuid

**Comment by Sim4n6** [comment]
References : 

- python implementation of ksuid https://github.com/saresend/KSUID/blob/master/ksuid/ksuid.py

**Comment by Sim4n6** [comment]
feel free to assign it to me :-)
