### ISSUE TITLE
Default build error, with fix?

### ISSUE THREAD

**Issue by knapjack** [obsidianforensics/unfurl#193]
Doing a standard build on multiple platforms, the result errors out with:

```
    from flask.scaffold import _endpoint_from_view_func
ModuleNotFoundError: No module named 'flask.scaffold'
```
after some searching and experimentation, I found if I:

```
pip uninstall flask-restx
pip install flask-restx
```

it replaces flask-restx-1.1.0 with flask-restx-1.2.0, which replaces werkszeug-3.0.1 with werkzeug-2.3.7 and the error goes away.

**Comment by obsidianforensics** [comment]
Thanks for the report! I'll try to put out a new release soon with the right versions of those dependencies.

**Comment by obsidianforensics** [comment]
This has been addressed in updated requirements files, and a new release with them incorporated will be out shortly. Thanks again for the report!
