### ISSUE TITLE
Mastodon Snowflakes

### ISSUE THREAD

**Issue by obsidianforensics** [obsidianforensics/unfurl#20]
**Description**
Mastodon is a social network that uses IDs similar to Snowflakes, so we should be able to pull out a timestamp.

**Examples**
- https://infosec.exchange/web/statuses/101767036616676231

**References**
- https://github.com/tootsuite/mastodon/blob/master/lib/mastodon/snowflake.rb
- https://github.com/tootsuite/mastodon/issues/1059
- https://theoria24.github.io/dt2sf/#/

**Comment by Sim4n6** [comment]
Hi, I am interested in this "First Issue". I am reading the code source right now ...  Please feel free to assign it #20 to me.

**Comment by obsidianforensics** [comment]
That's awesome, thanks! Will do.

**Comment by Sim4n6** [comment]
Commit a89c026898f21c65034188a0868c4807b828e80e sorry that I mixed the two PRs into  #26
