### ISSUE TITLE
Base64 False Positives

### ISSUE THREAD

**Issue by cstavros** [obsidianforensics/unfurl#202]
Some websites are unfurled with a base64 protocol reference in the graph; however, no such inclusion exists in the URL.

For example, when unfurling `https://example.com/find/early`, this item is in the returned JSON:

```
"summary": {"URL Parsing Functions": 10,
            "Date & Time Parsing Functions": 1,
            "Parsed from base64, then as a protobuf": 1}
```

That adds a distinct `b64+proto` label to the visual representation which looks out of place:

![unfurl_graph](https://github.com/user-attachments/assets/257d5fda-8d5b-4891-b4a3-04bb960b249f)

**Comment by obsidianforensics** [comment]
I tightened up the parsing to not try to decode things that are all letters or all digits, plus the `/` character (to handle the case you found above). It's not perfect, but it's a balance between FPs and trying to parse unknown inputs. 

Thanks for flagging this, and if you find more, I'd be happy to revisit and try to make the parsing even better!
