### ISSUE TITLE
pytest or unittest for testing ?

### ISSUE THREAD

**Issue by Sim4n6** [obsidianforensics/unfurl#27]
**Description**
I would like to create a mechanism of testing. I suggest to use either Pytest, or Unittest.

Please, before I dive on working on the PR. Could you please choose the one that you recommend the most ?

**Comment by obsidianforensics** [comment]
I'd prefer unittest; I'm starting work on adding tests to Hindsight as well and am using it there too.

**Comment by Sim4n6** [comment]
I made an initial commit 987b1d0caa3d8913af8ef73ec9dfc28beb3010a1 for /tests/ (units). To run it please use ``python -m unittest discover -s tests``

**Comment by obsidianforensics** [comment]
Those tests look great, thanks! I think eventually there should be unit tests for every parser, and integration tests for bigger Unfurl functionality. If you want to keep working on either one, that'd be great. I'll try and get some CI stuff setup on here too so we can use the tests with every commit.

**Comment by Sim4n6** [comment]
Why not 👍
