### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by weslambert** [obsidianforensics/unfurl#40]
I've created a Dockerfile and `docker-compose` file for standing up unfurl in a Docker container.  However, it appears that even though we can change the host/port for unfurl in `config.ini`, if you are running via Docker etc, the `fetch` request [here](https://github.com/obsidianforensics/unfurl/blob/master/templates/graph.html#L114) refers to the explicit host/port as defined in `config.ini`.

This becomes an issue when you are trying to expose unfurl via `0.0.0.0` in the Docker container, and are trying to access unfurl via the browser via the host IP address (something like `192.168.1.199`, because unfurl is trying to fetch `0.0.0.0:5000`, instead of the host IP).

I've got a PR ready (from [here](https://github.com/weslambert/unfurl/tree/graph_host)) that replaces `unfurl_host`:`unfurl_port ` with:

`window.location.host` (host + port of current request) 

and provides the necessary files for running unfurl in a Docker container

See [here](https://github.com/weslambert/unfurl/commit/9d108cf4f1a779882a195a107845ea22667512d4#diff-1665afafe2221693c3d7ae3db0b437dbR114) for more details on the host/port change

This seems to work okay from my testing.

Any thoughts on potential issues with this, or how this could be done better to support Docker?

If this all sounds okay, I will go ahead and submit a PR -- just let me know!

**Comment by obsidianforensics** [comment]
That sounds great to me - thanks for working on this! I'm not very familiar with developing things for Docker, but the host name change you proposed makes sense and doesn't seem to break anything when run without Docker. 

PR would be great, thanks :+1:
