### ISSUE TITLE
Expand Short URLs

### ISSUE THREAD

**Issue by obsidianforensics** [obsidianforensics/unfurl#42]
**Description**
Consider implementing expansion of short URLs.
**Pro**: Lots of URL shortening services can hide interesting links. 
**Con:** We'd need to reach out to 3rd party sites to do this resolution (the data is not embedded in the URL).

**Comment by Sim4n6** [comment]
I am working on this for bitly url shortner.

**Comment by Sim4n6** [comment]
![unfurl](https://user-images.githubusercontent.com/13036531/73919098-2aac9f00-48c3-11ea-8253-093fc523e5da.png)

**Comment by x1mus** [comment]
Hello !
I don't know if it's the right place to ask, but I found 2 more short link domains that aren't integrated in the program.
- https://urlwee.com
- https://l0.cl
That's it for me :)
The first one is working with HTTP redirection, the other one is working with client site JS redirection.

**Comment by obsidianforensics** [comment]
Thanks! I'll take a look at them.
