### ISSUE TITLE
The explanation for the date/time parameters are wrong

### ISSUE THREAD

**Issue by Rasmus-Riis** [obsidianforensics/unfurl#56]
In the mouseover to the ei parameter it states that the ei parameter is believed to correspond to when the search took place. This is not correct. I have seen ei parameters hours apart from the actual search.

What I have gathered is, that the EI is session start (When the tab was opened)  or last search. If there is only 1 search immediately after tab opening it will roughly correspond to search time, but that is a coincidence

An example can be seen here:

https://www.google.com/search?sxsrf=ALeKk01OOv3qyJF_Sb7_1WIuBa-cNGDDNg%3A1587403446547&ei=ttqdXsP7IMKZk74Pgv-k6AY&q=third+search+at17%3A28&oq=third+search+at17%3A28&gs_lcp=CgZwc3ktYWIQA1DbihFYqeQRYPnmEWgAcAB4AIABfYgBthOSAQQyNC41mAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwjDrq_UwvfoAhXCzMQBHYI_CW0Q4dUDCAw&uact=5

I opened a tab and searched for 'First search at 17:22' (At 17:22 naturally).
I then searched for 'Second search at 17:24' 
Finally waited and searched for 'third search at 17:28'

So there is no indication of the actual search time.

**Comment by obsidianforensics** [comment]
Thank you for pointing this out and backing up your observation with an experiment! It's fantastic to have data to point to on things like this. I've updated the descriptions and also added a link to this issue as a reference.
