### ISSUE TITLE
Add cmd-c / rightclick shortcut to copy a selected node content

### ISSUE THREAD

**Issue by Maijin** [obsidianforensics/unfurl#58]
**Description**
When selecting a node, add the ability to cmd+c (ctrl+c) to copy the content of the node. 

**Optionnal** 

Add a right click "copy" ability

**Comment by obsidianforensics** [comment]
Thanks for filing the issue! This has been a rather annoying shortcoming for a while. I've implemented a simple copy function (https://github.com/obsidianforensics/unfurl/commit/df0dfb75da78fc92d7ef51d96dd7d71720e81f74). Right now, it's just double-click the node to copy the node label to the clipboard. 

Eventually I'd like a whole right-click menu with different options, but that's beyond me at the moment. This should make working with node data a bit easier in the meantime.
