### ISSUE TITLE
Add support for mailto URLs

### ISSUE THREAD

**Issue by OllieJC** [obsidianforensics/unfurl#78]
**Description**
Unfurl mailto URLs which behave very similar to `http` URLs but miss out the regular-looking scheme part (`mailto:` rather than `http://`, `s3://` etc.), so first take the data before `?` (if in string) and that is the `to` address(es) anything after the `?` can be treated like `url.query`.

**Examples**
- There's some examples in point 6 of the RFC: https://tools.ietf.org/html/rfc2368
- https://css-tricks.com/snippets/html/mailto-links/

**References**
- https://tools.ietf.org/html/rfc2368
- Started a parser here: [parse_mailto.py](https://github.com/OllieJC/unfurl/blob/master/unfurl/parsers/parse_mailto.py)
  - Initial example:
[![Imgur](https://i.imgur.com/2yJlHum.png)](https://i.imgur.com/2yJlHum.png)

**Comment by obsidianforensics** [comment]
Fixed by #79; thanks! The reference info in this issue is really helpful.
