### ISSUE TITLE
Parse YouTube URLs

### ISSUE THREAD

**Issue by obsidianforensics** [obsidianforensics/unfurl#80]
**Description**
There is some good data encoded in YouTube URLs. At a minimum, some links point to a particular time in a video. 

I'm happy to help/coach/answer questions if anyone wants to work on this issue!

**Examples**
- https://youtu.be/Xj1wG_M7yyg?t=19658

**References**
- The t param looks to be the number of seconds into the video

**Comment by kistee** [comment]
Hi.
I would like to work on this issue but am unsure how since this is my first time doing so for an open source project. Help would be appreciated for guiding me in the right direction for the first steps.

**Comment by obsidianforensics** [comment]
That's great! I'm glad you'd like to get involved. I'm going to be pretty scarce for the next week, but I'll try to be responsive to any questions. I'd suggest modeling the parser on a simpler existing one, like https://github.com/obsidianforensics/unfurl/blob/master/unfurl/parsers/parse_bing.py. I'll work on getting more of a guide together.

**Comment by kistee** [comment]
The approach, copying and adapting an already existing parser, is what I tried so far. My main issue is how to add a new parser. Because I couldn't figure that out yet, I couldn't test if what I'm doing is working or not.

**Comment by obsidianforensics** [comment]
Gotcha, makes sense. 

Steps to add a new parser, based off an existing one:
1. Copy the existing parser file and rename the new one (for example, in /unfurl/parsers, copy parse_bing.py to parse_youtube.py)
2. Edit the "run" function to do what you want to do (I know this is vague and I need to make a whole guide for it)
3. Edit /unfurl/parsers/\_\_init__.py and add the name of your new parser (example: parse_youtube)

Now when you run Unfurl, your new parse_youtube parser should run as well.

**Comment by kistee** [comment]
Thank you so much for helping me out!
I didn't see the `__init__.py` file, so that was the problem.

The next big issue is what to do in the "run" function as you already correctly assumed.
I'll try to see if I can figure it out myself or I'll wait until you made a guide on it.

Here's what i came up with for now:

````python
youtube_edge = {
    'color': {
        'color': '#ff0000'
    },
    'title': 'Youtube Parsing Functions',
    'label': 'Y'
}


def run(unfurl, node):
    youtube_domains = ['youtube.com', 'youtu.be']
    if any(youtube_domain in unfurl.find_preceding_domain(node) for youtube_domain in youtube_domains):
        if node.key == 't':
            param_text = f'The youtube video will begin playing at {str(node.value)} seconds.'
            unfurl.add_to_queue(
                data_type='descriptor', key=None, value=node.value, label=param_text,
                parent_id=node.node_id, incoming_edge_config=youtube_edge)
````

I figured I'd ask for your thoughts on it here first, before making a pull request. If that's the wrong way please tell me!

**Comment by obsidianforensics** [comment]
Looks pretty good! I'd suggest opening a pull request; there are some small tweaks I'd suggest and it's easier to do in a PR, but overall looks good.

**Comment by kistee** [comment]
Gotcha, just did so!
